#!/bin/bash
# ═══════════════════════════════════════════════════════════════
# Batch runner for C-V2X Mode 4 simulation scenarios
# ═══════════════════════════════════════════════════════════════
#
# Usage:
#   ./run_batch.sh <config1> [config2] [config3] ...
#
# Examples:
#   ./run_batch.sh _1_ECDSA_A_LOS _2_ECDSA_A_NLOS
#   ./run_batch.sh _13_Falcon_A_LOS _14_Falcon_A_NLOS
#   ./run_batch.sh Base
#
# What it does for each scenario:
#   1. Runs the simulation in command-line mode
#   2. Creates a timestamped folder in simulation_logs_storage/
#   3. Moves simulation_logs/* and results/<config>* there
# ═══════════════════════════════════════════════════════════════

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SIM_LOGS="$SCRIPT_DIR/simulation_logs"
LOG_STORAGE="$SCRIPT_DIR/simulation_logs_storage"
RESULTS="$SCRIPT_DIR/results"

# Colors for terminal output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

if [ $# -eq 0 ]; then
    echo -e "${RED}Error: No scenario names provided.${NC}"
    echo ""
    echo "Usage: $0 <config1> [config2] [config3] ..."
    echo ""
    echo "Available configs:"
    grep '^\[Config ' "$SCRIPT_DIR/omnetpp.ini" | sed 's/\[Config //;s/\]//' | column
    exit 1
fi

# Create storage directories if they don't exist
mkdir -p "$LOG_STORAGE"
mkdir -p "$RESULTS"

TOTAL=$#
CURRENT=0
FAILED=0
SUCCEEDED=0

echo ""
echo -e "${CYAN}═══════════════════════════════════════════════════════════${NC}"
echo -e "${CYAN}  Batch Simulation Runner — $TOTAL scenario(s) queued${NC}"
echo -e "${CYAN}═══════════════════════════════════════════════════════════${NC}"
echo ""

START_ALL=$(date +%s)

for CONFIG in "$@"; do
    CURRENT=$((CURRENT + 1))
    TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
    DEST="$LOG_STORAGE/${CONFIG}_${TIMESTAMP}"

    echo -e "${YELLOW}──────────────────────────────────────────────────────────${NC}"
    echo -e "${YELLOW}  [$CURRENT/$TOTAL] Running: ${CONFIG}${NC}"
    echo -e "${YELLOW}  Started: $(date '+%Y-%m-%d %H:%M:%S')${NC}"
    echo -e "${YELLOW}──────────────────────────────────────────────────────────${NC}"

    # Clean simulation_logs before run
    rm -f "$SIM_LOGS"/*.csv "$SIM_LOGS"/*.log 2>/dev/null || true

    # Run the simulation
    START_ONE=$(date +%s)

    if cd "$SCRIPT_DIR" && ./run -u Cmdenv -c "$CONFIG" -r 0; then
        END_ONE=$(date +%s)
        ELAPSED=$((END_ONE - START_ONE))
        MINS=$((ELAPSED / 60))
        SECS=$((ELAPSED % 60))
        echo ""
        echo -e "${GREEN}  ✓ ${CONFIG} completed in ${MINS}m ${SECS}s${NC}"
        SUCCEEDED=$((SUCCEEDED + 1))
    else
        END_ONE=$(date +%s)
        ELAPSED=$((END_ONE - START_ONE))
        MINS=$((ELAPSED / 60))
        SECS=$((ELAPSED % 60))
        echo ""
        echo -e "${RED}  ✗ ${CONFIG} FAILED after ${MINS}m ${SECS}s${NC}"
        FAILED=$((FAILED + 1))
    fi

    # Create destination folder and move outputs
    mkdir -p "$DEST/logs"
    mkdir -p "$DEST/results"

    # Move simulation logs (CSV files generated by Mode4App)
    if ls "$SIM_LOGS"/*.csv 1>/dev/null 2>&1; then
        mv "$SIM_LOGS"/*.csv "$DEST/logs/"
        echo "  → Logs moved to: ${DEST##*/}/logs/"
    fi
    if ls "$SIM_LOGS"/*.log 1>/dev/null 2>&1; then
        mv "$SIM_LOGS"/*.log "$DEST/logs/"
    fi

    # Move result files (.sca, .vec, .vci)
    if ls "$RESULTS"/${CONFIG}-* 1>/dev/null 2>&1; then
        mv "$RESULTS"/${CONFIG}-* "$DEST/results/"
        echo "  → Results moved to: ${DEST##*/}/results/"
    fi

    echo ""
done

END_ALL=$(date +%s)
TOTAL_ELAPSED=$((END_ALL - START_ALL))
TOTAL_MINS=$((TOTAL_ELAPSED / 60))
TOTAL_SECS=$((TOTAL_ELAPSED % 60))

echo -e "${CYAN}═══════════════════════════════════════════════════════════${NC}"
echo -e "${CYAN}  Batch complete: ${SUCCEEDED} succeeded, ${FAILED} failed${NC}"
echo -e "${CYAN}  Total time: ${TOTAL_MINS}m ${TOTAL_SECS}s${NC}"
echo -e "${CYAN}═══════════════════════════════════════════════════════════${NC}"
echo ""
echo "Output stored in: $LOG_STORAGE/"
ls -dt "$LOG_STORAGE"/*/ 2>/dev/null | head -$TOTAL
