#! /bin/sh
DIR=`dirname $0`
DIR=`(cd $DIR ; pwd)`
INET_DIR=`(cd $DIR/../../inet/src ; pwd)`
VEINS_SRC=`(cd $DIR/../../veins/src ; pwd)`
COMMAND_LINE_OPTIONS="-l $INET_DIR/INET -l $VEINS_SRC/veins -n $DIR/../simulations:$DIR:$INET_DIR:$VEINS_SRC/veins"

if [ -x $DIR/lte -o -x $DIR/lte.exe ]; then
  $DIR/lte $COMMAND_LINE_OPTIONS $*
else
  opp_run -l $DIR/lte $COMMAND_LINE_OPTIONS $*
fi
