//
// Generated file, do not edit! Created by nedtool 5.7 from apps/mode4App/BSM.msg.
//

#ifndef __BSM_M_H
#define __BSM_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0507
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>apps/mode4App/BSM.msg:2</tt> by nedtool.
 * <pre>
 * message BSM
 * {
 *     int32_t msgId;
 *     double latitude;
 *     double longitude;
 *     double heading;
 *     double speed;
 * }
 * </pre>
 */
class BSM : public ::omnetpp::cMessage
{
  protected:
    int32_t msgId;
    double latitude;
    double longitude;
    double heading;
    double speed;

  private:
    void copy(const BSM& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const BSM&);

  public:
    BSM(const char *name=nullptr, short kind=0);
    BSM(const BSM& other);
    virtual ~BSM();
    BSM& operator=(const BSM& other);
    virtual BSM *dup() const override {return new BSM(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int32_t getMsgId() const;
    virtual void setMsgId(int32_t msgId);
    virtual double getLatitude() const;
    virtual void setLatitude(double latitude);
    virtual double getLongitude() const;
    virtual void setLongitude(double longitude);
    virtual double getHeading() const;
    virtual void setHeading(double heading);
    virtual double getSpeed() const;
    virtual void setSpeed(double speed);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const BSM& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, BSM& obj) {obj.parsimUnpack(b);}


#endif // ifndef __BSM_M_H

