//
// Generated file, do not edit! Created by nedtool 5.7 from veins/pqcdsa/BSM.msg.
//

#ifndef __BSM_M_H
#define __BSM_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0507
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef VEINS_API
#  if defined(VEINS_EXPORT)
#    define VEINS_API  OPP_DLLEXPORT
#  elif defined(VEINS_IMPORT)
#    define VEINS_API  OPP_DLLIMPORT
#  else
#    define VEINS_API
#  endif
#endif



class BSM;
/**
 * Class generated from <tt>veins/pqcdsa/BSM.msg:2</tt> by nedtool.
 * <pre>
 * message BSM
 * {
 *     // --- J2735 BSMcoreData (Part I) — fully compliant ---
 *     uint8_t msgCnt = 0;              // MsgCount (0-127)                         1B
 *     int32_t msgId;                   // simulation-only PDR tracking             4B (not in J2735)
 *     string tempId = "";             // TemporaryID (4-octet hex)                4B wire
 *     uint16_t secMark = 0;            // DSecond (ms within minute, 0-65535)      2B
 *     int32_t lat = 0;                // Latitude  (OMNeT coord in mm: m * 1000)  4B
 *     int32_t lon = 0;                // Longitude (OMNeT coord in mm: m * 1000)  4B
 *     int16_t elev = 0;               // Elevation (0.1m, -4096..61439)           2B
 * 
 *     // PositionalAccuracy (J2735: 4 bytes total)
 *     uint8_t semiMajor = 255;        // 0.05m units (255=unavailable)            1B
 *     uint8_t semiMinor = 255;        // 0.05m units (255=unavailable)            1B
 *     uint16_t semiMajorOrient = 65535; // 360/65535 deg (65535=unavailable)        2B
 * 
 *     uint8_t transmission = 7;       // TransmissionState (7=unavailable)        1B
 *     uint16_t speed_j = 8191;         // Speed (0.02 m/s, 8191=unavailable)       2B
 *     uint16_t heading_j = 28800;      // Heading (0.0125 deg, 28800=unavailable)  2B
 *     int8_t angle = 127;            // SteeringWheelAngle (127=unavailable)     1B
 * 
 *     // AccelerationSet4Way (J2735: 7 bytes total)
 *     int16_t accelLong = 2001;       // 0.01 m/s^2 (-2000..2001, 2001=unavail)  2B
 *     int16_t accelLat = 2001;        // 0.01 m/s^2 (-2000..2001, 2001=unavail)  2B
 *     int8_t accelVert = -127;       // 0.02 G (-127..127, -127=unavailable)     1B
 *     int16_t yawRate = 0;            // 0.01 deg/s (-32767..32767)               2B
 * 
 *     // BrakeSystemStatus (J2735: 2 bytes total)
 *     uint16_t brakes = 0;            // packed bitfield (all unavailable)         2B
 * 
 *     // VehicleSize (J2735: 3 bytes total)
 *     uint16_t vehWidth = 0;          // 0.01m (0-1023, 0=unavailable)            2B
 *     uint8_t vehLength = 0;         // 0.1m (0-255, mapped from 0-4095)         1B
 * }
 * </pre>
 */
class VEINS_API BSM : public ::omnetpp::cMessage
{
  protected:
    uint8_t msgCnt = 0;
    int32_t msgId = 0;
    omnetpp::opp_string tempId = "";
    uint16_t secMark = 0;
    int32_t lat = 0;
    int32_t lon = 0;
    int16_t elev = 0;
    uint8_t semiMajor = 255;
    uint8_t semiMinor = 255;
    uint16_t semiMajorOrient = 65535;
    uint8_t transmission = 7;
    uint16_t speed_j = 8191;
    uint16_t heading_j = 28800;
    int8_t angle = 127;
    int16_t accelLong = 2001;
    int16_t accelLat = 2001;
    int8_t accelVert = -127;
    int16_t yawRate = 0;
    uint16_t brakes = 0;
    uint16_t vehWidth = 0;
    uint8_t vehLength = 0;

  private:
    void copy(const BSM& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const BSM&);

  public:
    BSM(const char *name=nullptr, short kind=0);
    BSM(const BSM& other);
    virtual ~BSM();
    BSM& operator=(const BSM& other);
    virtual BSM *dup() const override {return new BSM(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual uint8_t getMsgCnt() const;
    virtual void setMsgCnt(uint8_t msgCnt);
    virtual int32_t getMsgId() const;
    virtual void setMsgId(int32_t msgId);
    virtual const char * getTempId() const;
    virtual void setTempId(const char * tempId);
    virtual uint16_t getSecMark() const;
    virtual void setSecMark(uint16_t secMark);
    virtual int32_t getLat() const;
    virtual void setLat(int32_t lat);
    virtual int32_t getLon() const;
    virtual void setLon(int32_t lon);
    virtual int16_t getElev() const;
    virtual void setElev(int16_t elev);
    virtual uint8_t getSemiMajor() const;
    virtual void setSemiMajor(uint8_t semiMajor);
    virtual uint8_t getSemiMinor() const;
    virtual void setSemiMinor(uint8_t semiMinor);
    virtual uint16_t getSemiMajorOrient() const;
    virtual void setSemiMajorOrient(uint16_t semiMajorOrient);
    virtual uint8_t getTransmission() const;
    virtual void setTransmission(uint8_t transmission);
    virtual uint16_t getSpeed_j() const;
    virtual void setSpeed_j(uint16_t speed_j);
    virtual uint16_t getHeading_j() const;
    virtual void setHeading_j(uint16_t heading_j);
    virtual int8_t getAngle() const;
    virtual void setAngle(int8_t angle);
    virtual int16_t getAccelLong() const;
    virtual void setAccelLong(int16_t accelLong);
    virtual int16_t getAccelLat() const;
    virtual void setAccelLat(int16_t accelLat);
    virtual int8_t getAccelVert() const;
    virtual void setAccelVert(int8_t accelVert);
    virtual int16_t getYawRate() const;
    virtual void setYawRate(int16_t yawRate);
    virtual uint16_t getBrakes() const;
    virtual void setBrakes(uint16_t brakes);
    virtual uint16_t getVehWidth() const;
    virtual void setVehWidth(uint16_t vehWidth);
    virtual uint8_t getVehLength() const;
    virtual void setVehLength(uint8_t vehLength);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const BSM& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, BSM& obj) {obj.parsimUnpack(b);}

#endif // ifndef __BSM_M_H

