//
// Generated file, do not edit! Created by nedtool 5.7 from veins/pqcdsa//Certificate.msg.
//

#ifndef __CERTIFICATE_M_H
#define __CERTIFICATE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0507
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef VEINS_API
#  if defined(VEINS_EXPORT)
#    define VEINS_API  OPP_DLLEXPORT
#  elif defined(VEINS_IMPORT)
#    define VEINS_API  OPP_DLLIMPORT
#  else
#    define VEINS_API
#  endif
#endif



class Certificate;
/**
 * Class generated from <tt>veins/pqcdsa//Certificate.msg:2</tt> by nedtool.
 * <pre>
 * message Certificate
 * {
 *     // --- CertificateBase ---
 *     uint8_t version = 3;
 *     uint8_t certType = 0;           // 0=explicit
 *     uint8_t issuerType = 0;         // 0=sha256AndDigest, 1=self
 *     uint8_t issuerDigest[8];        // HashedId8 of issuing CA
 * 
 *     // --- ToBeSignedCertificate ---
 *     string subjectId = "";          // CertificateId (kept for debug)
 *     uint8_t cracaId[3];             // HashedId3
 *     uint16_t crlSeries = 0;
 *     int64_t validityStart = 0;       // Time32 (seconds since epoch)
 *     int64_t validityDuration = 0;    // Duration (seconds)
 *     uint32_t appPermPsid = 0x20;      // appPermissions PSID
 * 
 *     // --- VerifyKeyIndicator ---
 *     string algoName = "";
 *     uint8_t publicKey[];
 * }
 * </pre>
 */
class VEINS_API Certificate : public ::omnetpp::cMessage
{
  protected:
    uint8_t version = 3;
    uint8_t certType = 0;
    uint8_t issuerType = 0;
    uint8_t issuerDigest[8] = {0};
    omnetpp::opp_string subjectId = "";
    uint8_t cracaId[3] = {0};
    uint16_t crlSeries = 0;
    int64_t validityStart = 0;
    int64_t validityDuration = 0;
    uint32_t appPermPsid = 0x20;
    omnetpp::opp_string algoName = "";
    uint8_t *publicKey = nullptr;
    size_t publicKey_arraysize = 0;

  private:
    void copy(const Certificate& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Certificate&);

  public:
    Certificate(const char *name=nullptr, short kind=0);
    Certificate(const Certificate& other);
    virtual ~Certificate();
    Certificate& operator=(const Certificate& other);
    virtual Certificate *dup() const override {return new Certificate(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual uint8_t getVersion() const;
    virtual void setVersion(uint8_t version);
    virtual uint8_t getCertType() const;
    virtual void setCertType(uint8_t certType);
    virtual uint8_t getIssuerType() const;
    virtual void setIssuerType(uint8_t issuerType);
    virtual size_t getIssuerDigestArraySize() const;
    virtual uint8_t getIssuerDigest(size_t k) const;
    virtual void setIssuerDigest(size_t k, uint8_t issuerDigest);
    virtual const char * getSubjectId() const;
    virtual void setSubjectId(const char * subjectId);
    virtual size_t getCracaIdArraySize() const;
    virtual uint8_t getCracaId(size_t k) const;
    virtual void setCracaId(size_t k, uint8_t cracaId);
    virtual uint16_t getCrlSeries() const;
    virtual void setCrlSeries(uint16_t crlSeries);
    virtual int64_t getValidityStart() const;
    virtual void setValidityStart(int64_t validityStart);
    virtual int64_t getValidityDuration() const;
    virtual void setValidityDuration(int64_t validityDuration);
    virtual uint32_t getAppPermPsid() const;
    virtual void setAppPermPsid(uint32_t appPermPsid);
    virtual const char * getAlgoName() const;
    virtual void setAlgoName(const char * algoName);
    virtual void setPublicKeyArraySize(size_t size);
    virtual size_t getPublicKeyArraySize() const;
    virtual uint8_t getPublicKey(size_t k) const;
    virtual void setPublicKey(size_t k, uint8_t publicKey);
    virtual void insertPublicKey(uint8_t publicKey);
    virtual void insertPublicKey(size_t k, uint8_t publicKey);
    virtual void erasePublicKey(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Certificate& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Certificate& obj) {obj.parsimUnpack(b);}

#endif // ifndef __CERTIFICATE_M_H

