//
// Generated file, do not edit! Created by nedtool 5.7 from veins/pqcdsa/IcaSpdu.msg.
//

#ifndef __ICASPDU_M_H
#define __ICASPDU_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0507
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef VEINS_API
#  if defined(VEINS_EXPORT)
#    define VEINS_API  OPP_DLLEXPORT
#  elif defined(VEINS_IMPORT)
#    define VEINS_API  OPP_DLLIMPORT
#  else
#    define VEINS_API
#  endif
#endif



class IcaSpdu;
#include "IcaWarn_m.h" // import IcaWarn

#include "Certificate_m.h" // import Certificate

/**
 * Class generated from <tt>veins/pqcdsa/IcaSpdu.msg:6</tt> by nedtool.
 * <pre>
 * packet IcaSpdu extends cPacket
 * {
 *     // --- Ieee1609Dot2Data ---
 *     uint8_t protocolVersion = 3;
 * 
 *     // --- HeaderInfo ---
 *     uint32_t psid = 0x40;             // ICA PSID
 *     int64_t generationTime = 0;      // microsec since 2004-01-01 UTC
 *     int32_t genLocation_lat = 0;
 *     int32_t genLocation_lon = 0;
 *     int16_t genLocation_elev = 0;
 * 
 *     // --- ToBeSignedData.payload ---
 *     IcaWarn warn;
 * 
 *     // --- SignerIdentifier ---
 *     uint8_t signerType = 1;          // 0=digest, 1=certificate, 2=self
 *     uint8_t signerDigest[8];         // HashedId8 (when signerType=0)
 *     Certificate cert;                   // included when signerType=1
 * 
 *     // --- Signature ---
 *     uint8_t signature[];
 * }
 * </pre>
 */
class VEINS_API IcaSpdu : public ::omnetpp::cPacket
{
  protected:
    uint8_t protocolVersion = 3;
    uint32_t psid = 0x40;
    int64_t generationTime = 0;
    int32_t genLocation_lat = 0;
    int32_t genLocation_lon = 0;
    int16_t genLocation_elev = 0;
    IcaWarn warn;
    uint8_t signerType = 1;
    uint8_t signerDigest[8] = {0};
    Certificate cert;
    uint8_t *signature = nullptr;
    size_t signature_arraysize = 0;

  private:
    void copy(const IcaSpdu& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const IcaSpdu&);

  public:
    IcaSpdu(const char *name=nullptr, short kind=0);
    IcaSpdu(const IcaSpdu& other);
    virtual ~IcaSpdu();
    IcaSpdu& operator=(const IcaSpdu& other);
    virtual IcaSpdu *dup() const override {return new IcaSpdu(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual uint8_t getProtocolVersion() const;
    virtual void setProtocolVersion(uint8_t protocolVersion);
    virtual uint32_t getPsid() const;
    virtual void setPsid(uint32_t psid);
    virtual int64_t getGenerationTime() const;
    virtual void setGenerationTime(int64_t generationTime);
    virtual int32_t getGenLocation_lat() const;
    virtual void setGenLocation_lat(int32_t genLocation_lat);
    virtual int32_t getGenLocation_lon() const;
    virtual void setGenLocation_lon(int32_t genLocation_lon);
    virtual int16_t getGenLocation_elev() const;
    virtual void setGenLocation_elev(int16_t genLocation_elev);
    virtual const IcaWarn& getWarn() const;
    virtual IcaWarn& getWarnForUpdate() { return const_cast<IcaWarn&>(const_cast<IcaSpdu*>(this)->getWarn());}
    virtual void setWarn(const IcaWarn& warn);
    virtual uint8_t getSignerType() const;
    virtual void setSignerType(uint8_t signerType);
    virtual size_t getSignerDigestArraySize() const;
    virtual uint8_t getSignerDigest(size_t k) const;
    virtual void setSignerDigest(size_t k, uint8_t signerDigest);
    virtual const Certificate& getCert() const;
    virtual Certificate& getCertForUpdate() { return const_cast<Certificate&>(const_cast<IcaSpdu*>(this)->getCert());}
    virtual void setCert(const Certificate& cert);
    virtual void setSignatureArraySize(size_t size);
    virtual size_t getSignatureArraySize() const;
    virtual uint8_t getSignature(size_t k) const;
    virtual void setSignature(size_t k, uint8_t signature);
    virtual void insertSignature(uint8_t signature);
    virtual void insertSignature(size_t k, uint8_t signature);
    virtual void eraseSignature(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const IcaSpdu& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, IcaSpdu& obj) {obj.parsimUnpack(b);}

#endif // ifndef __ICASPDU_M_H

