//
// Generated file, do not edit! Created by nedtool 5.7 from veins/pqcdsa/SPDU.msg.
//

#ifndef __SPDU_M_H
#define __SPDU_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0507
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef VEINS_API
#  if defined(VEINS_EXPORT)
#    define VEINS_API  OPP_DLLEXPORT
#  elif defined(VEINS_IMPORT)
#    define VEINS_API  OPP_DLLIMPORT
#  else
#    define VEINS_API
#  endif
#endif



class SPDU;
#include "BSM_m.h" // import BSM

#include "Certificate_m.h" // import Certificate

/**
 * Class generated from <tt>veins/pqcdsa/SPDU.msg:5</tt> by nedtool.
 * <pre>
 * packet SPDU extends cPacket
 * {
 *     BSM bsm;              // nested message
 *     uint8_t signature[];   // raw bytes (666 for Falcon-512)
 *     Certificate cert;             // sender’s certificate
 * }
 * </pre>
 */
class VEINS_API SPDU : public ::omnetpp::cPacket
{
  protected:
    BSM bsm;
    uint8_t *signature = nullptr;
    size_t signature_arraysize = 0;
    Certificate cert;

  private:
    void copy(const SPDU& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SPDU&);

  public:
    SPDU(const char *name=nullptr, short kind=0);
    SPDU(const SPDU& other);
    virtual ~SPDU();
    SPDU& operator=(const SPDU& other);
    virtual SPDU *dup() const override {return new SPDU(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const BSM& getBsm() const;
    virtual BSM& getBsmForUpdate() { return const_cast<BSM&>(const_cast<SPDU*>(this)->getBsm());}
    virtual void setBsm(const BSM& bsm);
    virtual void setSignatureArraySize(size_t size);
    virtual size_t getSignatureArraySize() const;
    virtual uint8_t getSignature(size_t k) const;
    virtual void setSignature(size_t k, uint8_t signature);
    virtual void insertSignature(uint8_t signature);
    virtual void insertSignature(size_t k, uint8_t signature);
    virtual void eraseSignature(size_t k);
    virtual const Certificate& getCert() const;
    virtual Certificate& getCertForUpdate() { return const_cast<Certificate&>(const_cast<SPDU*>(this)->getCert());}
    virtual void setCert(const Certificate& cert);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SPDU& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SPDU& obj) {obj.parsimUnpack(b);}

#endif // ifndef __SPDU_M_H

